### ISSUE TITLE
Version of the app that can just extract passwords from the Keychain with Touch ID only

### ISSUE THREAD

**Issue by timkgh** [remko/age-plugin-se#3]
Is it possible to make a version of this app that can extract a password from a macOS custom (non-login) keychain? The macOS `security` command always asks for password only which makes it annoying to script. It would be nice to have a command that can work with a custom keychain that can read a password from the keychain auth'ed with Touch ID only and output it so it can be piped into another script, temporarily stored in an env variable, etc.

One immediate application would be [termotp](https://github.com/marcopaganini/termotp), without involving `age` at all, we could just store the Aegis password directly in the Keychain. Nothing wrong with `age` or `age-plugin-se`, in fact I'm grateful they both exist, but the fewer moving parts the better.

**Comment by remko-bw** [comment]
Hi @timkgh ,

What you're describing sounds like a different tool, with almost no overlap with what this plugin does.

This plugin doesn't use the macOS keychain, but talks to the secure enclave directly, which is explained in [the Design document](https://github.com/remko/age-plugin-se/blob/main/Documentation/Design.md#secureenclave-apis-security-vs-cryptokit). It's possible you can create a different small tool that uses the Security framework, although I didn't check that the API allows you to decrypt keys using just Touch ID, and note that such a tool is harder to distribute due to required entitlements (as mentioned in the design document).

**Comment by remko** [comment]
Hi @timkgh ,

What you're describing sounds like a different tool, with almost no overlap with what this plugin does.

This plugin doesn't use the macOS keychain, but talks to the secure enclave directly, which is explained in [the Design document](https://github.com/remko/age-plugin-se/blob/main/Documentation/Design.md#secureenclave-apis-security-vs-cryptokit). It's possible you can create a different small tool that uses the Security framework, although I didn't check that the API allows you to decrypt keys using just Touch ID, and note that such a tool is harder to distribute due to required entitlements (as mentioned in the design document).

**Comment by timkgh** [comment]
I see, makes sense. Thanks for the explanation.
