### ISSUE TITLE
Update Homebrew Tap version

### ISSUE THREAD

**Issue by timkgh** [remko/age-plugin-se#4]
It seems stuck at 0.0.4

Also, any chance to push it into the homebrew core repo?

Thank you.

**Comment by remko** [comment]
Hi @timkgh 

I didn't update the Homebrew formula, because nothing happened that had an impact on the macOS binary.
However, since everything is stable, I just rolled a v0.1.0 release, and updated the Homebrew tap to also use this latest version.

Now that there's a 'stable' version, I'd like to get it into Homebrew core at some point, but the project doesn't have enough stars yet (the minimum requirement is 75). Once I reach the threshold, I'll submit it.
